set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT STREQUAL "opencv4")
	set(VCPKG_CMAKE_CONFIGURE_OPTIONS
		-DBUILD_LIST=core,imgproc,imgcodecs,videoio
		-DCPU_BASELINE=SSE4_2
		-DCPU_DISPATCH=
		-DWITH_IMGCODEC_GIF=OFF
		-DWITH_IMGCODEC_HDR=OFF
		-DWITH_IMGCODEC_PFM=OFF
		-DWITH_IMGCODEC_PXM=OFF
		-DWITH_IMGCODEC_SUNRASTER=OFF
		-DVIDEOIO_ENABLE_PLUGINS=OFF
		-DENABLE_LTO=ON
	)
endif()
